spring:
  data:
    mongodb:
      uri: mongodb+srv://${DB_USER:admin}:${DB_PASSWORD}@wfcoursecluster.5uzsima.mongodb.net/${DB_NAME:wf-course}?retryWrites=true&w=majority&appName=WfCourseCluster
      auto-index-creation: true
  application:
    name: wf-course